from enum import Enum


class AgentState(str, Enum):
    INITIALIZING = "INITIALIZING"
    ANALYZING = "ANALYZING"
    RETRIEVING = "RETRIEVING"
    REQUESTING_ACTION = "REQUESTING_ACTION"
    VALIDATING_ACTION = "VALIDATING_ACTION"
    EXECUTING_TOOL = "EXECUTING_TOOL"
    OBSERVING = "OBSERVING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
